//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageTour
    {
        public int TourId { get; set; }
        public string TourName { get; set; }
        public string Duration { get; set; }
        public string TourRoute { get; set; }
        public Nullable<int> TourStyle { get; set; }
        public string ActivityLevel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SortDescription { get; set; }
        public string Detail { get; set; }
        public Nullable<double> GuestPrice { get; set; }
        public Nullable<double> AgencyPrice2 { get; set; }
        public Nullable<double> AgencyPrice1 { get; set; }
        public Nullable<bool> Remove { get; set; }
        public Nullable<bool> Special { get; set; }
        public string Image { get; set; }
    }
}
