//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectTour
    {
        public int SelectTourId { get; set; }
        public string TourName { get; set; }
        public string Detail { get; set; }
        public Nullable<double> AgencyStandard2 { get; set; }
        public Nullable<double> AgencyStandard35 { get; set; }
        public Nullable<double> AgencyStandard69 { get; set; }
        public Nullable<double> AgencySuperior2 { get; set; }
        public Nullable<double> AgencySuperior35 { get; set; }
        public Nullable<double> AgencySuperior69 { get; set; }
        public Nullable<double> Agency2Standard2 { get; set; }
        public Nullable<double> Agency2Standard35 { get; set; }
        public Nullable<double> Agency2Standard69 { get; set; }
        public Nullable<double> Agency2Superior2 { get; set; }
        public Nullable<double> Agency2Superior35 { get; set; }
        public Nullable<double> Agency2Superior69 { get; set; }
        public Nullable<double> GuestStandard2 { get; set; }
        public Nullable<double> GuestStandard35 { get; set; }
        public Nullable<double> GuestStandard69 { get; set; }
        public Nullable<double> GuestSuperior2 { get; set; }
        public Nullable<double> GuestSuperior35 { get; set; }
        public Nullable<double> GuestSuperior69 { get; set; }
        public Nullable<bool> Remove { get; set; }
        public Nullable<bool> Special { get; set; }
        public Nullable<int> Style { get; set; }
        public string Duration { get; set; }
        public string TourRoute { get; set; }
        public Nullable<double> AgencyDeluxe2 { get; set; }
        public Nullable<double> AgencyDeluxe35 { get; set; }
        public Nullable<double> AgencyDeluxe69 { get; set; }
        public Nullable<double> Agency2Deluxe2 { get; set; }
        public Nullable<double> Agency2Deluxe35 { get; set; }
        public Nullable<double> Agency2Deluxe69 { get; set; }
        public Nullable<double> GuestDeluxe2 { get; set; }
        public Nullable<double> GuestDeluxe35 { get; set; }
        public Nullable<double> GuestDeluxe69 { get; set; }
        public string Image { get; set; }
        public string SortDescription { get; set; }
    }
}
